### ISSUE TITLE
Plugin and theme compatibility bug woodmart version 5.3.6 + ReviewX 1.2.5

### ISSUE THREAD

**Issue by Grishin-M** [reviewx/Contribute#11]
Hi there! We are using woodmart version 5.3.6 theme and your plugin version 1.2.5.

We have an error displaying orders in our personal account. You can see screenshots. On the left in the screenshot, you can see what the orders look like when the ReviewX plugin is disabled. Right when turned on

We also use the YITH plugin "Configure my account page", at first we thought there was a conflict between the two plugins, but we tried to deactivate it and the result is the same. Woodmart theme compatibility bug
![bug](https://user-images.githubusercontent.com/10217069/106121400-976e1880-6168-11eb-95af-b218dbee3e31.jpg)

**Comment by amin-abir** [comment]
Hi @IIoIIa 

Sorry for your inconvenience.
We have checked and made ReviewX compatible with Woodmart theme, previously. But there could be an issue for version changing of the theme. Please allow us some time, to check this.

Thanks for your nice explanation.

Regards

Amin

**Comment by Grishin-M** [comment]
also we found one more bug. it concerns changing the color of the scheme
If we change the color of the scheme from the standard blue to any other, then at the bottom the pagination remains blue
![color-cheme](https://user-images.githubusercontent.com/10217069/106134211-4285ce80-6177-11eb-9f81-df7e3fd40e1a.jpg)

**Comment by amin-abir** [comment]
Ok, let us check this also, just for a query, are you using WordPress customizer or Elementor/ Oxygen page builder.

**Comment by Grishin-M** [comment]
We use WPBakery Page Builder

**Comment by Grishin-M** [comment]
Hi there! Do you have any good news for solving the above problems? When can we expect an update with fixed bugs?

**Comment by amin-abir** [comment]
Hi, 
The issue is actually yith my account plugin and reviewx design issue, not with woodmart theme, but we can fix it as the issue is found.
We have scheduled release next week. We will fix the issue with this release.

I will inform you, once we released the update, thanks for your patience and cooperation.

Amin

**Comment by amin-abir** [comment]
Hi @IIoIIa 

After analyzing we have found that the design break in my account page is not for ReviewX, the issue was for 'Yith customize my account plugin' with 'Woodmart theme', you can check by disabling ReviewX.

However, we have solved this design issue for you, please paste the following CSS on your WordPress customizer> additional CSS section.

#my-account-menu {
    width: 100%;
    box-sizing: border-box;
}

For the pagination coloring effect issue, please contact our support. https://reviewx.io/support/

Thanks for your patience & cooperation.

Regards
