### ISSUE TITLE
Added Features Request: Points, Rating Slider, Reviewer Attributes

### ISSUE THREAD

**Issue by zabdala** [reviewx/Contribute#20]
ReviewX has been great for me so far in configuring my site. While I do like the stars feature, I'd like the option for using **points** rather than stars for more granular statistics in the reviews. 

Additionally, I have been looking for a way to better convey issues, for garment sizing as an example. This can be done through predefined tags available to the reviewer ("too small" or "too large" etc.)  or through a **slider**. And allowing for fields for reviewer **attributes** would add to this. 

An example of where I've seen this type of review is on ae.com:
https://www.ae.com/us/en/p/women/jegging/high-waisted-jegging/ae-dream-high-waisted-jegging/0433_2654_053?menu=cat4840004

**Comment by amin-abir** [comment]
Hi @zabdala 

Good to know you like ReviewX. 👍🏻 

Thanks for this awesome feature suggestion. I think you want to display numbers rather than the stars rating. Yes, we can give an option like this in the settings, so the store owner can set what he/she wants to display. 

The slider option is also a good idea, I think it will be mainly applicable for those stores that sell garments.

I am passing these suggestions to our R&D team.

Thanks again for using ReviewX and giving us these feature suggestions. 😊
