### ISSUE TITLE
missing hooks - message translation needed - into german

### ISSUE THREAD

**Issue by Schmidtworks** [reviewx/Contribute#3]
The widget allows no translation in other languages - how can i adjust the language inside rewiewX widgets ?
![Bildschirmfoto 2020-09-30 um 20 24 37](https://user-images.githubusercontent.com/48754943/94724784-12f6bf00-035b-11eb-8fff-4a87c629a939.png)

i need to translate the messages into german.

thanx for your feedback

**Comment by amin-abir** [comment]
Hi @Schmidtworks 
Please allow us some time to check this scenario, and if any string is missing then, we will make it translation ready and let you know.

Thanks

**Comment by Schmidtworks** [comment]
Thanx for your work. - please let me know when an update is available.

**Comment by Schmidtworks** [comment]
[translation-options_needed_reviewX_011020.pdf](https://github.com/reviewx/Contribute/files/5309881/translation-options_needed_reviewX_011020.pdf)

There are much more messages and tags to make adjustable for translation. - Your recommended "LOCO plugin", don't show me these options for individual translation of these parts. - or can you help me to find the tags via LOCO - Thanx for your feedback.

**Comment by amin-abir** [comment]
Hi @Schmidtworks 

I make this video for you regarding translating into German Language, 
https://www.loom.com/share/62e05849bdea4639ae6d84d676aad171

In your shared pdf those strings are also translatable, just need to translate in your language. As we said you can use 'Loco Translate' plugin.

For using  'Loco Translate' you can see these too:
https://zemez.io/wordpress/support/how-to/manage-plugins-translations-using-loco-translate-plugin-2/
https://www.youtube.com/watch?v=6qLkdl97PU0

Thanks

**Comment by amin-abir** [comment]
Hi @Schmidtworks 

We did not hear from you regarding your translation problem. We hope your problem is solved.

Just to inform you that, We have released a new version of ReviewX free and pro. 
ReviewX free: 1.1.13
ReviewX Pro: 1.0.18

We have introduced some new features like Separate settings to enable 'External & Internal' video attachment, Send & Cancel action for all WooCommerce reminder emails, a new shortcode for custom profile image uploader.

we hope you will enjoy it.

Thanks
